[NSA-8656] Add dropdown to deactivate invited user view and update tests
DFE-Digital/login.dfe.support pull request #509
Opened 2024-11-15 13:59 UTC by alexplattdfe

Link to ticket: [NSA-8656](https://dfe-secureaccess.atlassian.net/browse/NSA-8656)

Following on from NSA-8523, add a dropdown menu to the deactivate invited users view to allow a support user to select a common reason for deactivating a user.

2024-11-18 10:29 UTC, Lakorthus submitted a review, later dismissed
Looks good 👍

2024-11-18 12:28 UTC, insacuri requested changes
LGTM, but can you add a unit test to simulate both an option being selected AND a reason typed in the box.  It's useful, almost as documentation, to show what the intended functionality of it is

2024-11-20 09:51 UTC, insacuri approved these changes

2024-11-21 09:54 UTC, JaredAMarsh approved these changes
Looks good to me as it matches the user flow 😄

My one question is what happens if neither field are submitted? E.g. if someone went into DevTools and removed both fields? Obviously support is internal and no one is going to want to do that 😂 It was more a getting you thinking kind of question 😃

2024-11-21 12:32 UTC, merged