Feature/improve more unit tests
DFE-Digital/login.dfe.support pull request #513
Opened 2024-11-19 17:30 UTC by insacuri

2024-12-02 08:29 UTC, AMcCartneyMTH submitted a review, later dismissed

2024-12-02 14:14 UTC, JaredAMarsh requested changes
Overall, the tests are good and cover the expected responses from the APIs and what we expect to go with the requests, I've added comments/requested changes purely for some of the naming and some of the items the test say it's doing are not being checked as far as I can see 😃

2024-12-02 14:14 UTC, JaredAMarsh commented on test/infrastructure/applications/api.getPageOfService.test.js
> +  it('should return false on a 404 response', async () => {
The test message here says "return false" but the result is actually checked to see if it's "undefined" 😄

2024-12-02 14:14 UTC, JaredAMarsh commented on test/infrastructure/applications/api.isSupportEmailNotificationAllowed.test.js
> +  it('then it should call users resource with user id', async () => {
Does this test use the user ID as referenced in the message? Just a check, as I can't see it below.

2024-12-02 14:14 UTC, JaredAMarsh commented on test/infrastructure/applications/api.isSupportEmailNotificationAllowed.test.js
> +  it('then it should include the correlation id', async () => {
This doesn't currently include a correlation ID, and this check is identical to the one above 😄

2024-12-02 14:14 UTC, JaredAMarsh commented on test/infrastructure/directories/api.createInvite.test.js
> +  it('then it should call user codes resource with uid', async () => {
The user ID isn't checked for in the request body or URL 😄

2024-12-02 14:14 UTC, JaredAMarsh commented on test/infrastructure/directories/api.getChangeEmailCode.test.js
> +describe('when getting a page of users from directories api', () => {
Is this description correct? 😄

2024-12-02 14:14 UTC, JaredAMarsh commented on test/infrastructure/directories/api.getUsersByIdV2.test.js
> +  it('then it calls directories api with Ids', async () => {
This has a POST because the IDs are passed through the body, this check doesn't check for the IDs like the description states 😄

2024-12-02 14:14 UTC, JaredAMarsh commented on test/infrastructure/directories/api.reactivate.test.js
> +describe('when deactivating an invite from the directories api', () => {
*Reactivating, and I believe this test is for a user not an invite 👍

2024-12-02 14:14 UTC, JaredAMarsh commented on test/infrastructure/directories/api.resendInvite.test.js
> +describe('when getting a page of users from directories api', () => {
This is for resending an invitation 👍

2024-12-02 14:14 UTC, JaredAMarsh commented on test/infrastructure/directories/api.updateInvite.test.js
> +describe('when getting a page of users from directories api', () => {
This is for updating an invitation 👍

2024-12-03 09:25 UTC, JaredAMarsh approved these changes

2024-12-03 10:06 UTC, alexplattdfe approved these changes
LGTM

2024-12-03 10:07 UTC, merged